version: '3.8'

services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  data_processor:
    build: .
    volumes:
      - ./app:/app
      - ./scripts:/scripts
      - ./config:/config
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    # 手動実行用: docker-compose run data_processor python data_fetcher.py

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data: