services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./config:/config:ro  # 設定ファイル用（次のステップで使用）
      - ./utils:/app/utils:ro
      - ./tests:/app/tests:ro  
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      EDINET_API_KEY: ${EDINET_API_KEY} # 環境変数でAPIキーを設定
    # リソース制限（セキュリティ強化）
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped

  data_processor:
    build: .
    command: sleep infinity
    volumes:
      - ./scripts:/scripts:ro
      - ./config:/app/config:ro
      - ./utils:/app/utils:ro
      - ./download:/download:ro
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

  db:
    image: postgres:15-alpine  # より軽量で新しいバージョン
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    # セキュリティ強化
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

volumes:
  db_data:
